#pragma once

#include "sdkconfig.h"  // Include SDK configuration generated by IDF build system

// WiFi credentials
#ifndef CONFIG_WIFI_SSID
    #define CONFIG_WIFI_SSID "StefanIOT"  // Default SSID
#endif

#ifndef CONFIG_WIFI_PASSWORD
    #define CONFIG_WIFI_PASSWORD "stefaniot"  // Default password
#endif

// MQTT server configuration
#ifndef CONFIG_MQTT_BROKER
    #define CONFIG_MQTT_BROKER "mqtt://192.168.1.93"  // Default broker
#endif

#define MQTT_PORT 1883  // Port can be hardcoded if not meant to be configurable

#ifndef CONFIG_MQTT_USERNAME
    #define CONFIG_MQTT_USERNAME ""  // Default MQTT username
#endif

#ifndef CONFIG_MQTT_PASSWORD
    #define CONFIG_MQTT_PASSWORD ""  // Default MQTT password
#endif

// MQTT topics
#ifndef CONFIG_MQTT_RESPONSE_TOPIC
    #define CONFIG_MQTT_RESPONSE_TOPIC "temperature/publish"
#endif

#ifndef CONFIG_MQTT_COMMAND_TOPIC
    #define CONFIG_MQTT_COMMAND_TOPIC "device/commands"
#endif

// Struct definition
typedef struct {
    int num_responses;
    int delay;
    uint32_t current_time;  // Using uint32_t to store time in milliseconds or similar
} TaskParameters;
