#pragma once

#include "sdkconfig.h"  // Include SDK configuration generated by IDF build system

// WiFi credentials
#ifndef WIFI_SSID
    #define WIFI_SSID "StefanIOT"  // Default SSID
#endif

#ifndef WIFI_PASSWORD
    #define WIFI_PASSWORD "stefaniot"  // Default password
#endif

// MQTT server configuration
#ifndef MQTT_BROKER
    #define MQTT_BROKER "mqtt://192.168.1.93"  // Default broker
#endif

#define MQTT_PORT 1883  // Port can be hardcoded if not meant to be configurable

#ifndef MQTT_USERNAME
    #define MQTT_USERNAME ""  // Default MQTT username
#endif

#ifndef MQTT_PASSWORD
    #define MQTT_PASSWORD ""  // Default MQTT password
#endif

// MQTT topics
#ifndef MQTT_RESPONSE_TOPIC
    #define MQTT_RESPONSE_TOPIC "temperature/publish"
#endif

#ifndef MQTT_COMMAND_TOPIC
#define MQTT_COMMAND_TOPIC "device/commands"
#endif

// Struct definition
typedef struct {
    int num_responses;
    int delay;
    uint32_t current_time;  // Using uint32_t to store time in milliseconds or similar
} TaskParameters;
